FROM mcr.microsoft.com/devcontainers/base:ubuntu24.04

RUN apt update && apt upgrade -y
RUN apt install -y jq curl
COPY install_zig.sh /install_zig.sh

USER vscode
WORKDIR /home/vscode

RUN /install_zig.sh

RUN curl -o toolchain.tar.gz https://static.dev.sifive.com/dev-tools/freedom-tools/v2020.12/riscv64-unknown-elf-toolchain-10.2.0-2020.12.8-x86_64-linux-ubuntu14.tar.gz
RUN mkdir ~/.local/riscv
RUN tar -xvf toolchain.tar.gz --strip-components 1 -C ~/.local/riscv
RUN echo 'export PATH=$PATH:$HOME/.local/riscv/bin' >> ~/.bashrc
